import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en" className="">
      <body className="bg-amber-50">
        {/* Global layout: header, footer, etc. */}
        {children}
      </body>
    </html>
  );
}
